apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:<REGION>:<ACCOUNT_ID>:certificate/<CERTIFICATE_ID>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  labels:
    run: protobuf-demo
  name: protobuf-demo
  namespace: default
spec:
  ports:
  - name: https
    nodePort: 31781
    port: 443
    protocol: TCP
    targetPort: 80
  - name: http
    nodePort: 31782
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: protobuf-demo
  sessionAffinity: None
  type: LoadBalancer
